### ISSUE TITLE
Message without value

### ISSUE THREAD

**Issue by mindthump** [gruns/icecream#53] opened 2021-01-26 20:10 UTC
I'd like to print the location with a simple message, but without the value. This can give better context to the location without extraneous output. Example:
`ic("Flag check.")`
prints
`ic| main.py:29 in prepare()- "Flag check.": 'Flag check.'`
I'd like a simple way to print
`ic| main.py:29 in prepare()- "Flag check."`

**Comment by alexmojaki** [comment] 2021-01-26 21:16
This could be done pretty easily - don't print the value if the argument is a literal, i.e. `ast.literal_eval` doesn't raise an exception.

**Comment by gruns** [comment] 2021-01-26 21:46
great catch! this is a subtle bug

simple values (numbers, strings, etc) are are already printed value-only, eg

```python
> ic(3)
```

outputs `ic| 3`, not `ic| 3: 3`. the subtle bug is that the `argument == value` check compares the argument string to the value string, eg the argument string `"Flag check."` and its value string 'Flag check.'`, produced with `repr()`). the two strings aren't equal because the former has double quotes and the latter single quotes

simple example exhibiting this behavior:

```python
#!/usr/bin/env python3.6
# -*- coding: utf-8 -*-

from icecream import ic

ic.configureOutput(includeContext=True)

ic(3)
ic('Flag check.')
ic("Flag check.")
```

prints

```
ic| test.py:11 in <module>| 3
ic| test.py:12 in <module>| 'Flag check.'
ic| test.py:13 in <module>| "Flag check.": 'Flag check.'
```

before I add a special case for strings that ignores differences in single and double quotes, can you think of any other datatypes where the delimiters would differ like strings?

**Comment by gruns** [comment] 2021-01-26 21:49
> This could be done pretty easily - don't print the value if the argument is a literal, i.e. ast.literal_eval doesn't raise an exception.

this is a superior solution to the immediate problem with strings, but it doesn't accommodate custom objects where the `repr()` (or implicitly `str()`) method produces a value string identical to the argument string

still, it's a simpler solution that works without exceptions to the rule (eg no exception for strings required)

**Comment by alexmojaki** [comment] 2021-01-26 21:58
> this is a superior solution to the immediate problem with strings, but it doesn't accommodate custom objects where the repr() (or implicitly str()) method produces a value string identical to the argument string

If you had a variable `foo` whose repr() happens to be `foo` that might be surprising enough that seeing it confirmed with `foo: foo` is useful information. If it just says `foo` by itself you might think icecream is broken.

**Comment by gruns** [comment] 2021-01-26 22:17
> If you had a variable foo whose repr() happens to be foo that might be surprising enough that seeing it confirmed with foo: foo is useful information. If it just says foo by itself you might think icecream is broken.

I would find `ic| foo: foo` no less confusing

still, I like the `ast.literal_eval` check for its simplicity. and it solves the problem 99% of the time

I'll add that

**Comment by gruns** [comment] 2021-01-27 01:30
fixed in icecream v2.1.0

upgrade with `pip install icecream --upgrade`

thank you Ed, and, as always, Alex :+1:

**Closed by gruns** 2021-01-27 01:30 UTC

**Comment by mindthump** [comment] 2021-01-28 02:00
Thanks! I didn't even notice the quote difference. I was going to look at a fix myself, but you all are too quick! 💯

**Comment by gruns** [comment] 2021-01-28 02:33
thank you for using icecream!
