### ISSUE TITLE
ic| Error: Failed to access the underlying source code for analysis.

### ISSUE THREAD

**Issue by mhechthz** [gruns/icecream#169] opened 2023-12-04 07:28 UTC
This was already in the issues but nevertheless I face this currently.

```
from icecream import ic

a = 3
b = 4
ic(a+b)
```

`ic| Error: Failed to access the underlying source code for analysis. Was ic() invoked in a REPL (e.g. from the command line), a frozen application (e.g. packaged with PyInstaller), or did the underlying source code change during execution?`

Windows 10, Python 3.11.6. On the same machine **Python 3.10** and **Python 3.12** work fine, but 3.11 not.
```
python -VV
Python 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
```

**Comment by char101** [comment] 2023-12-06 11:42
Works for me with python 3.11.6 on Windows. You cound testing if executing works first e.g.

```python
import inspect

import executing


def test(expr):
    source = executing.Source.executing(inspect.currentframe().f_back)
    print(source.text()) # should print `test(a + b)`


a = 3
b = 4
test(a + b)
```

If it doesn't work then the problem is in executing, then you could debug the `Source` class in executing.

**Comment by TheStrangerDoctor** [comment] 2023-12-14 13:46
Please close this issue if it is solved to prevent comment cluttering. TQ

**Comment by RainerFaller** [comment] 2024-01-04 21:08
I had the same problem with a fresh venv and Python 3.11.7. I resolved it by replacing the complete /site-packages/executing folder by the most recent source distribution 2.0.1

**Comment by vddo** [comment] 2024-02-07 08:59
I had the same problem and it was also resolved after reinstalling executing with pip. Had a look at the dependencies when installing with 'conda install conda-forge::icecream' shown on anaconda.org

Dependency when installing via conda-forge:
executing          pkgs/main/noarch::executing-0.8.3-pyhd3eb1b0_0

Can tell that this version is not working for icecream.

**Closed** 2024-11-07 06:44 UTC

**Comment by salabim** [comment] 2024-11-07 06:50
See an implementation on www.salabim.org/peek/

**Comment by gruns** [comment] 2024-11-07 06:59
@salabim did you mean to post https://github.com/gruns/icecream/issues/169#issuecomment-2461452780 in https://github.com/gruns/icecream/issues/186?

**Comment by RainerFaller** [comment] 2024-11-07 07:13
AnsgarNo, I did resolve my issue already some time ago as I mentioned in #169. Thank you for the great work. RainerAm 07.11.2024 um 16:00 schrieb Ansgar Grunseid ***@***.***>:﻿
@salabim did you mean to post #169 (comment) in #186?

**Comment by salabim** [comment] 2024-11-07 10:02
> @salabim did you mean to post [#169 (comment)](https://github.com/gruns/icecream/issues/169#issuecomment-2461452780) in #186?

Yes.

**Comment by xiezhipeng-git** [comment] 2024-12-01 13:40
This problem still exists.In the latest version, however, it can be fixed by
```
pip install -U executing
```
This means that a minimum version of executing is required

**Comment by salabim** [comment] 2024-12-01 14:03
Ir would be nice to just embed executing et all in icecream, so you don't have any dependencies, like in peek (www.salaim.org/peek).
