### ISSUE TITLE
OSError：could not get source code

### ISSUE THREAD

**Issue by misakichan** [gruns/icecream#17] opened 2018-03-28 08:48 UTC
Hi，gruns：
    I installed icecream win pip.

### my code

> from icecream import ic
> 
> ic(1)

### It not work and:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/icecream/icecream.py", line 322, in __call__
>     out = self._format(callFrame, *args)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/icecream/icecream.py", line 346, in _format
>     context = self._formatContext(callFrame, icNames, icMethod)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/icecream/icecream.py", line 435, in _formatContext
>     callFrame, icNames, icMethod)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/icecream/icecream.py", line 453, in _getContext
>     _, lineNumber, _ = getCallSourceLines(icNames, icMethod, callFrame)
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/icecream/icecream.py", line 144, in getCallSourceLines
>     parentBlockSource = ''.join(inspect.findsource(code)[0])
>   File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/inspect.py", line 756, in findsource
>     raise OSError('could not get source code')
> OSError: could not get source code

## My environment:

- MacOS 10.13.3
- Python3.6.1
- icecream1.3

**Comment by gruns** [comment] 2018-03-29 23:47
I can't reproduce this error with Python v3.6.1.

Did you execute that snippet in a Python REPL, not a file? IceCream requires a
file's source to inspect. When run in a REPL, without a file, IceCream currently
can't inspect the source of a REPL to extract its call arguments and thusn
OSError is raised.

```pycon
$ python -c "from icecream import ic; ic(1)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/icecream/icecream.py", line 310, in __call__
    icWithArgs(callFrame, icNames, args, self._printOut)
  File "/usr/local/lib/python2.7/dist-packages/icecream/icecream.py", line 277, in icWithArgs
    callSource, _, callSourceOffset = getCallSourceLines(icNames, callFrame)
  File "/usr/local/lib/python2.7/dist-packages/icecream/icecream.py", line 103, in getCallSourceLines
    parentBlockSource = ''.join(inspect.findsource(code)[0])
  File "/usr/lib/python2.7/inspect.py", line 538, in findsource
    raise IOError('could not get source code')
IOError: could not get source code
```

Is this what's happening?

**Comment by misakichan** [comment] 2018-04-17 01:06
@gruns yeah,when I use icecream in my python source file.it is work. 
「OSError」 only happen in bash command line.•ू(ᵒ̴̶̷ωᵒ̴̶̷*•ू) ​ )੭ु⁾

**Comment by gruns** [comment] 2018-04-19 06:47
Great -- thank you for confirmation.

Perhaps in the future IceCream will support terminal and REPL usage, but that's for a future version.

Closing for now.

**Closed by gruns** 2018-04-19 06:47 UTC
