### ISSUE TITLE
After printing a None value with ic(), text background color is not reset

### ISSUE THREAD

**Issue by jfid** [gruns/icecream#80] opened 2021-04-23 12:14 UTC
Consider the code:
```python
a = [1, 2, 3]
b = None
c = 3

ic(a)
ic(b)
ic(c)
```
After None is printed in the screen (Windows with Python 3.9.2), background color is not reset and anything printed afterwards gets the background color:

<img width="130" alt="capt01" src="https://user-images.githubusercontent.com/203650/115869260-ecef5400-a43d-11eb-8393-0ef23cc244e4.png">

**Comment by alexmojaki** [comment] 2021-04-23 12:24
Duplicate of #35

**Closed by alexmojaki** 2021-04-23 12:24 UTC
